---
name: sergioaugrod
title: sergioaugrod
description: Programação e pão de queijo
meta_description: Programação e pão de queijo
markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
domain_name: https://www.sergioaugrod.com.br
google_analytics: UA-80000306-1
gems:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-admin
url: https://www.sergioaugrod.com.br
base_url: "/"
author: Sérgio Rodrigues
lang: pt_BR
