name: sergioaugrod
description: Programação e pão de queijo
meta_description: 'Programação e pão de queijo'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: /
domain_name: 'http://www.sergioaugrod.com.br'
google_analytics: 'UA-80000306-1'
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

# Details for the RSS feed generator
url:            'http://www.sergioaugrod.com.br'
author:         'Sérgio Rodrigues'

# SEO
lang: 'pt_BR'
